#!/usr/bin/env bash
# Script that configure Nginx for redirection

sudo apt update
sudo apt -y install nginx
echo 'Hi!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=dQw4w9WgXcQ&t=145s&ab_channel=RickAstley;}' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
